Feat/harbor
conquer-project/conquer_platform pull request #10
Opened 2023-10-22 13:39 UTC by benhur-araujo

- we'll need to change the instance type, even with t3.micro 12 workers node there is not enough RAM to deploy harbor.
- Harbor creates Statefulsets with PVCs. We need aws-ebs-csi-driver add-on in place

2023-10-22 18:34 UTC, carlosgit2016 approved these changes

2023-10-22 18:41 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/eks-control-plane.tf
> +resource "aws_eks_addon" "aws-ebs-csi-driver" {
Looks like this plugin need permission to interact with AWS API to manage the volumes https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

2023-10-22 18:42 UTC, carlosgit2016 requested changes

2023-10-22 18:42 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/eks-control-plane.tf
> +resource "aws_eks_addon" "aws-ebs-csi-driver" {
Looks like this plugin need permission to interact with AWS API to manage the volumes https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

2023-10-22 18:45 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/eks-control-plane.tf
> +resource "aws_eks_addon" "aws-ebs-csi-driver" {
better info here https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#set-up-driver-permissions

2023-10-22 18:48 UTC, benhur-araujo commented on infrastructure/ephemeral-resources/eks-control-plane.tf
> +resource "aws_eks_addon" "aws-ebs-csi-driver" {
yes, working on it

2023-10-25 23:30 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/iam.tf
> +  eks-iodc-issuer = replace(aws_eks_cluster.eks.identity.0.oidc.0.issuer, "https://", "")
```suggestion
  oidc_issuer = replace(aws_eks_cluster.eks.identity.0.oidc.0.issuer, "https://", "")
```

2023-10-25 23:30 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/iam.tf
> +# ---------------------------------- EOF - EKS WORKER NODES ROLE --------------------------------
```suggestion
```

2023-10-25 23:30 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/iam.tf
> +#-------------------------- EOF - EBS CSI Driver IAM Role ------------------------------------
```suggestion
```

2023-10-25 23:33 UTC, carlosgit2016 commented on k8s-manifests/argocd-apps/harbor.yaml
> +  project: default  # ArgoCD Project. Let use default for now
Should it be per environment in the future ?

2023-10-25 23:35 UTC, carlosgit2016 commented on k8s-manifests/argocd-apps/harbor.yaml
> +      selfHeal: false   # git repo will always be the source of truth (any manual change on k8s will be overwritten)
Shouldn't we make it true ?

2023-10-27 03:25 UTC, carlosgit2016 commented on k8s-manifests/argocd-apps/harbor.yaml
> +      selfHeal: false   # git repo will always be the source of truth (any manual change on k8s will be overwritten)
nvm. I think we can kept this way for now

2023-10-28 21:55 UTC, benhur-araujo commented on k8s-manifests/argocd-apps/harbor.yaml
> +  project: default  # ArgoCD Project. Let use default for now
Thats a good idea

2023-10-28 22:23 UTC, carlosgit2016 approved these changes

2023-10-29 13:13 UTC, merged