feat(nginx): Added nginx controller and argocd nginx ingress
conquer-project/conquer_platform pull request #13
Opened 2023-10-26 02:14 UTC by carlosgit2016

2023-10-27 10:02 UTC, leohauschild commented on helm-charts/conquer-ingress/templates/ingress.yaml
Inside the argocd values, there is a block that you can use to create the ingress (example below), and I think it is easier because we don't need another file to apply.
```
server: 
  ingress:
    enabled: true
    annotations:
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - argocd.conquer-project.com
    paths:
      - /
    pathType: Prefix
    extraPaths: []
    tls:
      - secretName: argocd.conquer-project.com #If we use TLS (I use the same hostname to make it easier)
        hosts:
          - argocd.conquer-project.com

2023-10-27 10:13 UTC, leohauschild commented on k8s-manifests/argocd-apps/nginx-ingress-controller.yaml
You didn't use any values here, if you use an external source you can configure two sources and use a remote repository for the Chart and a local repository for the values.yaml.
[https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/](url)

2023-10-27 11:50 UTC, benhur-araujo requested changes

2023-10-27 11:50 UTC, benhur-araujo commented on helm-charts/conquer-ingress/.helmignore
move this file to helm-charts folder, so we will not need to create it for every chart

2023-10-27 11:50 UTC, benhur-araujo commented on helm-charts/conquer-ingress/templates/ingress.yaml
I agree, you will only need to add leo's suggestion here:
https://github.com/conquer-project/conquer_platform/pull/13/files#diff-a80d6e4ac36bcda6bc4eac602089a9b7cdd2be3c5e631f4485df944c09b81085

and this other file here:
https://github.com/conquer-project/conquer_platform/pull/13/files#diff-5e42c4e3553a422eab80e13de4110103a2366e4d967277fb64755d2816a04d3c

only those two modifications will be enough

2023-10-27 11:50 UTC, benhur-araujo commented on k8s-manifests/argocd-apps/nginx-ingress-controller.yaml
Nice tip, but I don't think we need to modify the default values now, so the current code is fine

2023-10-27 11:50 UTC, benhur-araujo commented on k8s-manifests/argocd-apps/nginx-ingress-controller.yaml
> +    server: https://kubernetes.default.svc
```
    namespace: kube-tools
```

2023-10-27 11:50 UTC, benhur-araujo commented on k8s-manifests/argocd-apps/nginx-ingress-controller.yaml
> +    targetRevision: 4.8.3
```suggestion
    targetRevision: 4.8.3
  syncPolicy:           # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:          
      prune: true       # will delete resources when Argo CD detects the resource is no longer defined in Git
      selfHeal: false   # git repo will always be the source of truth (any manual change on k8s will be overwritten)
      allowEmpty: false # do not allow argo applications have empty resource
    syncOptions:
      - CreateNamespace=true   # create kube-tools namespace if it doesn't exist
```

2023-10-31 05:12 UTC, carlosgit2016 commented on charts-overrides/nginx-controller/values.yaml
> +commonLabels:
Tested override 
![image](https://github.com/conquer-project/conquer_platform/assets/28971222/e01769ed-1b13-43ac-a615-9fa2f0f2d6b9)

2023-10-31 05:35 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/argocd-apps/values.yaml
> +      targetRevision: feat/nginx-ingress-argocd
- [ ] Change after approved

```suggestion
      targetRevision: main
```

2023-11-01 04:52 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/argocd-apps/values.yaml
> +        - $conquer/charts-overrides/nginx-controller/values.yaml
This link will not work, it must be a valid https/ssh git repository

2023-11-01 04:56 UTC, carlosgit2016 commented on charts-overrides/nginx-controller/values.yaml
I'm not a fan for this case, especially the argocd one. 

But I'll do, because doesn't matter for me

2023-11-01 05:26 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/argocd-apps/values.yaml
> +    - repoURL: https://github.com/conquer-project/conquer_platform.git
This is the repository where the values come from

2023-11-01 05:27 UTC, carlosgit2016 commented on infrastructure/ephemeral-resources/argocd-apps/values.yaml
> +      - ApplyOutOfSyncOnly=true
nice

2023-11-04 18:17 UTC, leohauschild commented on .github/workflows/create-ephemeral-resources.yml
> +          helm upgrade argocd argo-cd --install \
Here you run `helm upgrade` instead of `helm install`? or has argocd already been installed?

2023-11-04 18:17 UTC, leohauschild commented on .github/workflows/create-ephemeral-resources.yml
> +          helm upgrade argocd-apps argocd-apps --install \
Here the same.

2023-11-04 18:49 UTC, carlosgit2016 commented on .github/workflows/create-ephemeral-resources.yml
> +          helm upgrade argocd argo-cd --install \
I'm using the upgrade with `--install` that can install if this is not installed already or upgrade in case it is installed. That avoid problems when running with argocd already installed. I found this a better fit for our case

2023-11-04 18:53 UTC, leohauschild approved these changes

2023-11-05 00:13 UTC, benhur-araujo approved these changes

2023-11-05 01:12 UTC, merged